### ISSUE TITLE
NullPointerException when trying to initialize the driver in uber jar

### ISSUE THREAD

**Issue by bdw429s** [burningwave/jvm-driver#8]
I'm looking into using burningwave to help out a Java-based CLI tool which needs to support Java 16+.  I've added this line of code inside my main method
```
org.burningwave.core.assembler.StaticComponentContainer.Modules.exportAllToAll();
```
If I include the burningwave core and jvm-driver jars in the classpath, everything seems to be working at first blush.  However, my tool needs to be able to be called via 
```
java -jar mytool.jar
```
and therefore any libraries needed to bootstrap it are "shaded" into the main "uber" jar.  When I copy the class files, `banner.bwb` file and `jvm-driver.properties` file into my uber jar, I get this error.
```
io.github.toolfactory.jvm.util.ObjectProvider$BuildingException: Exception occurred while retrieving the implementation of class io.github.toolfactory.jvm.function.catalog.GetResourcesFunction (jvm architecture: x64, jvm version: 17, jvm vendor: Eclipse Adoptium)
        at io.github.toolfactory.jvm.util.ObjectProvider.getOrBuildObject(ObjectProvider.java:95)
        at io.github.toolfactory.jvm.DriverAbst.getOrBuildResourcesRetriever(DriverAbst.java:436)
        at io.github.toolfactory.jvm.DriverAbst.getResources(DriverAbst.java:884)
        at org.burningwave.core.io.Resources.lambda$getAsInputStream$3(Resources.java:160)
        at org.burningwave.core.io.Resources.getAsInputStream(Resources.java:165)
        at org.burningwave.core.io.Resources.getAsInputStream(Resources.java:158)
        at org.burningwave.core.assembler.StaticComponentContainer.showBanner(StaticComponentContainer.java:585)
        at org.burningwave.core.assembler.StaticComponentContainer.<clinit>(StaticComponentContainer.java:363)
        at cliloader.LoaderCLIMain.main(LoaderCLIMain.java:557)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at io.github.toolfactory.jvm.util.ObjectProvider.getOrBuildObjectInternal(ObjectProvider.java:144)
        at io.github.toolfactory.jvm.util.ObjectProvider.getOrBuildObject(ObjectProvider.java:92)
        ... 8 more
Caused by: io.github.toolfactory.jvm.util.ObjectProvider$BuildingException: Exception occurred while retrieving the implementation of class io.github.toolfactory.jvm.function.catalog.DeepConsulterSupplyFunction (jvm architecture: x64, jvm version: 17, jvm vendor: Eclipse Adoptium)
        at io.github.toolfactory.jvm.util.ObjectProvider.getOrBuildObject(ObjectProvider.java:95)
        at io.github.toolfactory.jvm.function.catalog.GetResourcesFunction$ForJava9.buildResourceFinder(GetResourcesFunction.java:129)
        at io.github.toolfactory.jvm.function.catalog.GetResourcesFunction$Abst.<init>(GetResourcesFunction.java:56)
        at io.github.toolfactory.jvm.function.catalog.GetResourcesFunction$ForJava7.<init>(GetResourcesFunction.java:92)
        at io.github.toolfactory.jvm.function.catalog.GetResourcesFunction$ForJava9.<init>(GetResourcesFunction.java:123)
        ... 15 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at io.github.toolfactory.jvm.util.ObjectProvider.getOrBuildObjectInternal(ObjectProvider.java:144)
        at io.github.toolfactory.jvm.util.ObjectProvider.getOrBuildObject(ObjectProvider.java:92)
        ... 19 more
Caused by: io.github.toolfactory.jvm.util.ObjectProvider$BuildingException: Exception occurred while retrieving the implementation of class io.github.toolfactory.jvm.function.catalog.GetDeclaredFieldFunction (jvm architecture: x64, jvm version: 17, jvm vendor: Eclipse Adoptium)
        at io.github.toolfactory.jvm.util.ObjectProvider.getOrBuildObject(ObjectProvider.java:95)
        at io.github.toolfactory.jvm.function.catalog.DeepConsulterSupplyFunction$ForJava14.<init>(DeepConsulterSupplyFunction.java:168)
        ... 26 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at io.github.toolfactory.jvm.util.ObjectProvider.getOrBuildObjectInternal(ObjectProvider.java:144)
        at io.github.toolfactory.jvm.util.ObjectProvider.getOrBuildObject(ObjectProvider.java:92)
        ... 27 more
Caused by: io.github.toolfactory.jvm.util.ObjectProvider$BuildingException: Exception occurred while retrieving the implementation of class io.github.toolfactory.jvm.function.catalog.GetDeclaredFieldsFunction (jvm architecture: x64, jvm version: 17, jvm vendor: Eclipse Adoptium)
        at io.github.toolfactory.jvm.util.ObjectProvider.getOrBuildObject(ObjectProvider.java:95)
        at io.github.toolfactory.jvm.function.catalog.GetDeclaredFieldFunction$ForJava7.<init>(GetDeclaredFieldFunction.java:45)
        ... 34 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at io.github.toolfactory.jvm.util.ObjectProvider.getOrBuildObjectInternal(ObjectProvider.java:144)
        at io.github.toolfactory.jvm.util.ObjectProvider.getOrBuildObject(ObjectProvider.java:92)
        ... 35 more
Caused by: io.github.toolfactory.jvm.util.ObjectProvider$BuildingException: Exception occurred while retrieving the implementation of class io.github.toolfactory.jvm.function.catalog.ConsulterSupplyFunction (jvm architecture: x64, jvm version: 17, jvm vendor: Eclipse Adoptium)
        at io.github.toolfactory.jvm.util.ObjectProvider.getOrBuildObject(ObjectProvider.java:95)
        at io.github.toolfactory.jvm.function.catalog.GetDeclaredFieldsFunction$ForJava7.<init>(GetDeclaredFieldsFunction.java:55)
        ... 42 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at io.github.toolfactory.jvm.util.ObjectProvider.getOrBuildObjectInternal(ObjectProvider.java:144)
        at io.github.toolfactory.jvm.util.ObjectProvider.getOrBuildObject(ObjectProvider.java:92)
        ... 43 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[])" because "input" is null
        at io.github.toolfactory.jvm.util.Streams.copy(Streams.java:48)
        at io.github.toolfactory.jvm.util.Streams.toByteArray(Streams.java:40)
        at io.github.toolfactory.jvm.function.catalog.ConsulterSupplyFunction$ForJava9.<init>(ConsulterSupplyFunction.java:82)
        ... 50 more
```

It's really hard to tell what all is going on there.  The `StaticComponentContainer.showBanner` portion of the outermost exception makes me think the issue is related to showing the banner.  

Things I've tried
* Ensured the `org/burningwave/banner.bwb` file exists inside my uber jar
* Tried to turn on the `banner.hide` setting but I'm not really sure how to do this (a system property would be MUCH easer than a properties file!)
  * I tried creating a `burningwave.static.properties` file in the root of my uber jar doesn't seem to get picked up
  * The docs say the properties file need to be located "_in the base path of your class path_" but I don't know what that means for my use case
  * I tried using the `setFileName()` method, but it's really unclear how that works.  Is it expecting a path inside the jar?  A relative path?  An absolute path?  Can it point anywhere on disk?  Does it need a prefix like `file://`?  I tried passing several things to `setFileName()`, including a non-existent path and it basically seems to just get ignored.

I really can't figure out how to debug any of this, and the stack traces in the error above are super confusing, lol.  

And furthermore, even if I can get past this banner error, I still have other questions such as how I can incorporate the `jvm-driver.properties` file from both of the required jvm-driver jars which are dependencies into a single uber-jar.

**Comment by Roberto-Gentili** [comment]
Hello, if you use **Burnignwave Core** with **Burningwave JVM-Driver** you need only the [jvm-driver.properties of the Burningwave JVM-Driver library](https://github.com/burningwave/jvm-driver/blob/main/java/src/main/resources/jvm-driver.properties). You need also to include all classes of ToolFactory JVM Driver. Try with these and let me know if you solved

**Comment by bdw429s** [comment]
Hi @Roberto-Gentili and thanks for the reply.  Honestly I have no clue which JVM driver I need nor what they even do, lol!  There really wasn't any docs that explained any of that and I just saw that both those drivers were included as Maven dependencies.  I have no idea what they do, why they are needed, how they differ, or why I'd want one over the other.

I followed the guide here
https://dev.to/jjbrt/how-to-avoid-resorting-to-add-exports-and-add-opens-in-jdk-16-and-later-j3m
which really doesn't explain anything other than how to call it.

Ether way, I feel like I've already tried what you are suggesting.  I copied ALL class files from the following jars into my uber jar

* `core-12.62.6.jar`
* `jvm-driver-8.14.1.jar`
* `jvm-driver-9.4.3.jar`

When you say "Burningwave JVM-Driver" and "ToolFactory JVM Driver", I'm just guessing that those correspond with the jars above.  All I know is what Maven downloaded, which is those jar names above, so the other descriptive names don't' really match anything I can see. (and I know nothing about this library :) ) 

Also, is there a reason you moved this to the jvm-driver repo?  The loading of config and displaying the banner seem to be part of the core, no?

**Comment by Roberto-Gentili** [comment]
You need to unpack all three jars and:

- take all `.class` files except the module-info.class
- take only the [jvm-driver.properties of the Burningwave JVM-Driver library](https://github.com/burningwave/jvm-driver/blob/main/java/src/main/resources/jvm-driver.properties)
- create a custom module-info.class where you merge all the module-info of all libraries you will include in uber.jar
- put the banner.bwb in the org/burningwave folder

**Comment by bdw429s** [comment]
Right, I did all of that initially with the exception of bullet # 3.  (I just picked a `module-info.class`.)  Perhaps that was the issue.  

I'm still a little skeptical since none of this seems to explain the error stack traces, why my config wasn't picked up, why the banner was trying to display, and why the input stream was null.  I would expect classdefnotfoud errors or similar if it was just a matter of missing class files.

**Comment by Roberto-Gentili** [comment]
I close the issue as it is not a library problem but a problem due to its manipulation

**Comment by bdw429s** [comment]
@Roberto-Gentili Thanks for all the help on this.  Unfortunately, I only had a few hours to look into this library and I'm out of time to keep troubleshooting right now.  I've just settled for a massive list of opens that I keep adding to.  If I'm able to come back to this and still have questions I'll reach out.  Please let me know if there's a better place to ask questions other than this ticket tracker.

**Comment by Roberto-Gentili** [comment]
> @Roberto-Gentili Thanks for all the help on this. Unfortunately, I only had a few hours to look into this library and I'm out of time to keep troubleshooting right now. I've just settled for a massive list of opens that I keep adding to. If I'm able to come back to this and still have questions I'll reach out. Please let me know if there's a better place to ask questions other than this ticket tracker.

If your report is not a library problem, for example, you can open a [discussion](https://github.com/burningwave/jvm-driver/discussions). Let's do one thing: I reopen the report and move it to discussions
